
######################## default configuration ####################
baseURL = "https://clowder.space/"
title = "Clowder"
enableRobotsTXT = true
DefaultContentLanguage = "en"
RemovePathAccents = true

googleAnalytics = "G-GRVWN5Y48L"

publishDir = "public/"

theme = "clowder"
# post pagination
paginate = "10"

[taxonomies]
tag = "tags"
category = "categories"
speaker = "speakers"
project = "projects"


# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link ="/plugins/color-switcher-design/color-switcher-design.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "/plugins/animate/animate.css"
[[params.plugins.css]]
link = "/plugins/flaticon/flaticon.css"
[[params.plugins.css]]
link = "https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"

#[[params.plugins.css]]
#link = "/plugins/style/style.css"


# JS Plugins

[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"

[[params.plugins.js]]
link="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"

[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"

[[params.plugins.js]]
link = "/plugins/jquery/jquery.countdown.js"

[[params.plugins.js]]
link="https://kit.fontawesome.com/2e09285ae6.js"

[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"

#[[params.plugins.js]]
#link="/plugins/owl/owl.js"

#[[params.plugins.js]]
#link="/plugins/wow/wow.js"

#[[params.plugins.js]]
#link="/plugins/parallax/parallax.min.js"

#[[params.plugins.js]]
#link="/plugins/script/script.js"





############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "PROJECTS"
  URL = "/projects"
  weight = 1

  [[menu.main]]
  identifier = "event"
  name = "Events"
  #URL = "/event-list/"
  weight = 2

  [[menu.main]]
    identifier = "program1"
    name = "Upcoming Events"
    URL = "/upcoming-events/"
    parent = "event"
    weight = 1

  [[menu.main]]
    identifier = "program2"
    name = "Previous Events"
    url = "/previous-events/"
    parent = "event"
    weight = 2

  [[menu.main]]
  name = "HOST A MEETUP"
  URL = "/host-meetup"
  weight = 3

  [[menu.main]]
  name = "BLOG"
  URL = "/blog"
  weight = 3

  #[[menu.main]]
  #name = "ABOUT"
  #URL = "/about"
  #weight = 4


#################### default parameters ################################
[params]
logo = "/images/Clowder-Space-Logo.png"
home = "Home"

# Meta data
description = "Coming soon."
image = "/images/Clowder_home.jpg"
images = ["/images/Clowder_home.jpg"]
twitter_user = ""
email = ""
author = ""

# search for blog page
search = true

disclaimer = ""

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Join our newsletter"
link = "https://forms.gle/3NcDqKk4g44ig8UUA"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/ClowderSpace"

#[[params.social]]
#icon = "tf-ion-social-youtube"
#link = "#"

#[[params.social]]
#icon = "fab fa-slack"
#link = "#"

[[params.social]]
icon = "tf-ion-android-mail"
link = "mailto:info@clowder.space"


[[params.social]]
icon = "fab fa-instagram"
link = "https://instagram.com/clowder.space?igshid=MTg0ZDhmNDA="

[[params.footer_about]]
name = "Know us"
link = "/about"

[[params.footer_about]]
name = "Contact us"
link = "mailto:info@clowder.space"

[[params.footer_about]]
name = "Brochure"
link = "/files/SG-DevRel-2023.pdf"

#[[params.footer_resources]]
#name = "Organizers"
#link = "#"

#[[params.footer_resources]]
#name = "Code of Conduct"
#link = "#"

#[[params.footer_resources]]
#name = "Privacy policy"
#link = "#"

#[[params.footer_resources]]
#name = "Call for papers"
#link = ""

#[[params.footer_resources]]
#name = "Partnership opportunities"
#link = ""






